### ISSUE TITLE
Approach incompatible with Tesla Powerwall

### ISSUE THREAD

**Issue by nicksantamaria** [ZimbiX/amber-enphase-zero-export-switcher-tool#1] opened 2023-01-03 22:53 UTC
Hi - this isn't a bug with the tool, but an issue with the approach when using enphase micros in the same system as a Tesla powerwall.

My setup includes
- 27 Q7 microinverters
- Envoy running version D5.0.62
- Tesla Powerwall 2

I set this tool up as-per the instructions. It definitely works as advertised - i.e. negative feed-in enables the 0 export grid profile. 

Unfortunately when the 0 export profile is enabled, it shuts down solar production and runs the house off the battery. Both the Tesla app and enlighten show 0 solar production when this occurs.

**Comment by nicksantamaria** [comment] 2023-01-04 04:51
After some experimentation, it appears the issue is that the Powerwall is much faster to respond to power draw, and takes over before solar can ramp up. This causes a negative feedback loop where solar production drops to nothing over a few minutes and then battery takes over entirely.

A work-around is to adjust the battery reserve level to 100% at the same time you switch to the 0 export grid profile.

And then adjust the battery reserve back to the standard 20% when standard export profile is enabled.

**Comment by ZimbiX** [comment] 2023-01-21 10:15
Thanks for the info, btw.

What did you end up using to switch the Powerwall battery reserve level at the point of switching the Envoy grid profile? If it was a code change to Zest, I'm thinking it'd be cleaner to add some sort of hook to support custom actions like that. So I'm about to add support for providing a custom command to run post-switch.

**Comment by ZimbiX** [comment] 2023-01-21 12:44
Done in 1cdc12d9c4feb4a5308206b8089e7bff6451de59. I think we can close this issue, given the problem is now mentioned in the readme and a custom command is supported. But I'm still interested to hear how you've set it up

**Closed as completed by ZimbiX** 2023-01-21 12:44 UTC

**Comment by purcell-lab** [comment] 2023-02-04 21:46
I had a similar problem with my SolarEdge inverters and Powerwall2 doing exactly this, running everything from the battery.

One issue I see with setting 100% SOC is the powerwall will draw any additional energy from the grid. This shouldn't be too bad as during negative FIT the grid price is very low anyway.

The solution I found was not to set 0W export, but to set 200W or 500W export on my solar inverter which would then work correctly with my powerwall and achieve the desired effect of maximising solar production including charging the powerwall but only exporting a minimal amount during negative FIT.

I'm unsure if this would require another profile with your enphase solution.

**Comment by shermozle** [comment] 2024-12-18 05:35
@nicksantamaria I know this is long closed but I worked with @ZimbiX to fix this and it's working nicely, using Home Assistant. Thanks for the help Brendan!

[Blog post](https://blog.simonrumble.com/disable-power-exporting-when-the-price-goes-negative-with-an-enphase-solar-inverter) and the [diff](https://gist.github.com/shermozle/2c8e833d8fe210a8da7d03d372eea734).
